server {
    listen 80;
    server_name nasaro-aws.duckdns.org;
    # Redirige todo el tráfico de http a https automáticamente
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nasaro-aws.duckdns.org;

    # Rutas a los certificados que acabas de generar
    ssl_certificate /etc/letsencrypt/live/nasaro-aws.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nasaro-aws.duckdns.org/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}