server {
    listen 80;
    server_name nasaro-aws.duckdns.org;
    
    # Redirige todo el tráfico de http a https automáticamente
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nasaro-aws.duckdns.org;

    # Rutas a los certificados de Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/nasaro-aws.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nasaro-aws.duckdns.org/privkey.pem;

    # Seguridad básica SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # PARTE 1: El Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # PARTE 2: El Backend (Proxy hacia el contenedor PHP)
    # Esto intercepta cualquier fetch que empiece por /controlador
    location /controlador/ {
        # 'backend' es el nombre del servicio en tu docker-compose.yml
        proxy_pass http://backend:80; 
        
        # Cabeceras necesarias para que PHP sepa quién le llama
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Evita el error 405 en métodos POST/PUT
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}